apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-git-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/ramanNarasimhan77/kcd-gitops-workshop.git
      revision: HEAD
      directories:
      - path: apps/*
      - path: apps/sync-waves
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ramanNarasimhan77/kcd-gitops-workshop.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true